package com.metecyu.flow.model;

// Generated 2013-7-15 11:23:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FlowInstance generated by hbm2java
 */
public class FlowInstance implements java.io.Serializable {

	private String id;
	private Flowdef flowdef;
	private String flowname;
	private Date createtime;
	private Date endtime;
	private String state;
	private String currnode;
	private Set tasks = new HashSet(0);

	public FlowInstance() {
	}

	public FlowInstance(Flowdef flowdef, String flowname, Date createtime,
			Date endtime, String state, String currnode, Set tasks) {
		this.flowdef = flowdef;
		this.flowname = flowname;
		this.createtime = createtime;
		this.endtime = endtime;
		this.state = state;
		this.currnode = currnode;
		this.tasks = tasks;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Flowdef getFlowdef() {
		return this.flowdef;
	}

	public void setFlowdef(Flowdef flowdef) {
		this.flowdef = flowdef;
	}

	public String getFlowname() {
		return this.flowname;
	}

	public void setFlowname(String flowname) {
		this.flowname = flowname;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCurrnode() {
		return this.currnode;
	}

	public void setCurrnode(String currnode) {
		this.currnode = currnode;
	}

	public Set getTasks() {
		return this.tasks;
	}

	public void setTasks(Set tasks) {
		this.tasks = tasks;
	}

}
