package com.metecyu.flow.model;

// Generated 11-八月-13 下午 05:40 by Hibernate Tools 3.4.0.CR1

/**
 * Node generated by hbm2java
 */
public class Node implements java.io.Serializable {

	private String id;
	private Flowdef flowdef;
	private String nodename;
	private int nodeno;

	public Node() {
	}

	public Node(Flowdef flowdef, String nodename, int nodeno) {
		this.flowdef = flowdef;
		this.nodename = nodename;
		this.nodeno = nodeno;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Flowdef getFlowdef() {
		return this.flowdef;
	}

	public void setFlowdef(Flowdef flowdef) {
		this.flowdef = flowdef;
	}

	public String getNodename() {
		return this.nodename;
	}

	public void setNodename(String nodename) {
		this.nodename = nodename;
	}

	public int getNodeno() {
		return this.nodeno;
	}

	public void setNodeno(int nodeno) {
		this.nodeno = nodeno;
	}

}
