package com.metecyu.flow.model;

// Generated 2013-7-15 11:23:12 by Hibernate Tools 3.4.0.CR1

/**
 * Node generated by hbm2java
 */
public class Node implements java.io.Serializable {

	private String id;
	private Flowdef flowdef;
	private String nodename;
	private String nodeno;

	public Node() {
	}

	public Node(Flowdef flowdef, String nodename, String nodeno) {
		this.flowdef = flowdef;
		this.nodename = nodename;
		this.nodeno = nodeno;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Flowdef getFlowdef() {
		return this.flowdef;
	}

	public void setFlowdef(Flowdef flowdef) {
		this.flowdef = flowdef;
	}

	public String getNodename() {
		return this.nodename;
	}

	public void setNodename(String nodename) {
		this.nodename = nodename;
	}

	public String getNodeno() {
		return this.nodeno;
	}

	public void setNodeno(String nodeno) {
		this.nodeno = nodeno;
	}

}
