package com.metecyu.flow.model;

// Generated 2013-7-15 11:23:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Flowdef generated by hbm2java
 */
public class Flowdef implements java.io.Serializable {

	private String id;
	private String flowname;
	private String flowno;
	private Set flowInstances = new HashSet(0);
	private Set nodes = new HashSet(0);

	public Flowdef() {
	}

	public Flowdef(String flowname, String flowno, Set flowInstances, Set nodes) {
		this.flowname = flowname;
		this.flowno = flowno;
		this.flowInstances = flowInstances;
		this.nodes = nodes;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFlowname() {
		return this.flowname;
	}

	public void setFlowname(String flowname) {
		this.flowname = flowname;
	}

	public String getFlowno() {
		return this.flowno;
	}

	public void setFlowno(String flowno) {
		this.flowno = flowno;
	}

	public Set getFlowInstances() {
		return this.flowInstances;
	}

	public void setFlowInstances(Set flowInstances) {
		this.flowInstances = flowInstances;
	}

	public Set getNodes() {
		return this.nodes;
	}

	public void setNodes(Set nodes) {
		this.nodes = nodes;
	}

}
